M48
; DRILL file {KiCad 7.0.9} date Thursday, December 14, 2023 at 03:35:26 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-14T15:35:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0945
%
G90
G05
T1
X8.26Y-3.5019
X8.26Y-3.62
T2
X6.4507Y-3.1975
X8.205Y-3.1975
T0
M30
